services:
  department-service:
    build:
      context: .
      dockerfile: department-service/Dockerfile
    ports:
      - "0:8080" # Replica instances will be available on a random port in the host
    environment:
        DB_HOST: postgres
        DB_PORT: 5432
        DB_NAME: management_db
        DB_USERNAME: admin_user
        DB_PASSWORD: password99
        EUREKA_SERVER_URL: http://eureka-server:8761/eureka
        KAFKA_SCHEMA_REGISTRY_URL: http://schemaregistry:8085
    depends_on:
      - postgres
      - eureka-server
      - kafka
      - schemaregistry
    networks:
      - spring
      - postgres
      - broker
    deploy:
      replicas: 1

  eureka-server:
      container_name: eureka-server
      build:
        context: .
        dockerfile: eureka-server/Dockerfile
      ports:
        - "8761:8761"
      networks:
        - spring

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: management_db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password99
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: unless-stopped

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.3.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: "2181"
      ZOOKEEPER_TICK_TIME: "2000"
      ZOOKEEPER_SERVERS: "zookeeper:22888:23888"
    restart: always
    networks:
      - broker

  kafka:
    container_name: kafka-broker
    image: confluentinc/cp-kafka:7.3.0
    ports:
      - "19092:19092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:19092
      KAFKA_BROKER_ID: 1
      KAFKA_BROKER_RACK: "r1"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_JMX_PORT: 9991
    depends_on:
      - zookeeper
    networks:
      - broker

  schemaregistry:
     container_name: schemaregistry
     image: confluentinc/cp-schema-registry:5.4.10
     ports:
       - 18085:8085
     environment:
       SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
       SCHEMA_REGISTRY_HOST_NAME: schemaregistry
       SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8085"
     depends_on:
       - zookeeper
     networks:
       - broker
     restart: always

  kafdrop:
    container_name: kafdrop
    image: obsidiandynamics/kafdrop:latest
    ports:
      - "19000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
      CMD_ARGS: "--message.format=AVRO --message.keyFormat=DEFAULT --schemaregistry.connect=http://schemaregistry:8085"
      KAFDROP_SERVER_PORT: 19000
    depends_on:
      - kafka
      - schemaregistry
    networks:
      - broker

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge
  broker:
    driver: bridge

volumes:
  postgres:
  pgadmin: