spring:
  application:
    name: department-service
  datasource:
    username: 'admin_user'
    url: jdbc:postgresql://localhost:5433/department_db
    password: 'password99'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
        ddl_auto: create
    show-sql: true

#server:
#  port: 8080
#  servlet:
#    context-path: /api